dataset: "LJSpeech"

val_size: 64

text:
    language: "en"
    text_cleaner: ['english_cleaners']

path:
    corpus_dir: "./corpus/LJSpeech-1.1"
    feature_dir: "./preprocessed_data/LJSpeech"


choice:
    norm_wav: True
    energy_phone_average: True
    f0_phone_average: True


audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
mel:
    n_mel_channels: 80
    mel_fmin: 0.0
    mel_fmax: 8000.0 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
